name: Helm Bake

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create App Specific Kubernetes Manifests
        uses: Azure/k8s-bake@v1
        id: bake
        with:
          renderEngine: 'helm'
          helmChart: './reviewer/'
          overrides: |     
            namespace: OVERRIDE_NAMESPACE
            vm.dnsPrefix: OVERRIDE_PREFIX
            vm.region: OVERRIDE_REGION
            release.repo: OVERRIDE_REPO
            release.name: OVERRIDE_NAME
            identity.api.resource: OVERRIDE_RESOURCE_API
            identity.api.client: OVERRIDE_CLIENT_API
            identity.ui.resource: OVERRIDE_RESOURCE_UI
            identity.ui.client: OVERRIDE_CLIENT_UI
          helm-version: 'latest'
          silent: 'false'

      - name: Publish manifest files
        uses: actions/upload-artifact@v2
        with:
          name: 'App Manifests'
          path: ${{ steps.bake.outputs.manifestsBundle }}
