name: Helm Bake

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create App Specific Kubernetes Manifests
        uses: Azure/k8s-bake@v1
        id: bake
        with:
          renderEngine: 'helm'
          helmChart: './reviewer/'
          overrides: |     
              namespace: testing
          helm-version: 'latest'
          silent: 'false'

      - name: Publish manifest files
        uses: actions/upload-artifact@v2
        with:
          name: 'App Manifests'
          path: ${{ steps.bake.outputs.manifestsBundle }}
